name: Bot SGA Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Instalar navegador Playwright
        run: npx playwright install --with-deps chromium

      - name: Ejecutar Bot SGA
        env:
          SGA_USER: ${{ secrets.SGA_USER }}
          SGA_PASS: ${{ secrets.SGA_PASS }}
          SHEETS_GET: ${{ secrets.SHEETS_GET }}
          SHEETS_POST: ${{ secrets.SHEETS_POST }}
        run: node bot.js
